### ISSUE TITLE
Need to use memset() to reinitialize existing arrays

### ISSUE THREAD

**Issue by mhightower83** [vtrust-de/esp8266-ota-flash-convert#5]
Initialization from brace-enclosed lists can only be done when the array is defined.
https://github.com/vtrust-de/esp8266-ota-flash-convert/blob/4af22dd61cc250b771331402face98a352c2a1b3/src/esp8266-ota-flash-convert.ino#L273-L274

These index past the end of the array and overwrite unknown variables with 0.

**Comment by kueblc** [comment]
Good point. I think I can remove these lines entirely since we're just using these as buffers that will be overwritten anyway. Thanks for writing in.

**Comment by kueblc** [comment]
BTW @khcnz this is an upstream bug (https://github.com/khcnz/Espressif2Arduino), though it doesn't look like upstream is being maintained anymore

**Comment by khcnz** [comment]
@kueblc thanks! I didn't know anyone was actively using a fork :)

Looks like my managed code background is showing through on that bug..
